# Generated by Django 5.0.1 on 2024-01-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Poroda')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opisanie')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Preview')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Klichka')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Preview')),
                ('video', models.TextField(blank=True, null=True, verbose_name='Url to video')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Poroda')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
            },
        ),
    ]
