# Generated by Django 5.0.1 on 2024-05-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('course', '0003_course_author_lesson_author'),
    ]

    operations = [
    ]
